//这个文件是你当前组件所在的路由位置

export const app = '/app'
export const home = '/app/home'
export const header = '/app/home/header'
export const headerNavigation = '/app/home/header/navigation'
export const homeContent = '/app/home/homeContent'
export const sourceR = '/app/home/source'
export const advertHome ='/app/home/advert'
export const sourceHome = '/app/home/source/sourceHome'
export const sourceSendHome = '/app/home/source/sourceSendHome'
export const fontEnd = '/app/home/font-end'
export const background = '/app/home/background'
export const game = '/app/home/game'
export const login = '/app/login'
export const bgTopTitle = '/app/home/background/background-top-title'
export const bgPageIntro = './app/home/background/background-page-intro'
export const bgPageMember = './app/home/background/background-page-member'
export const bgPageResources = '/app/home/background/background-page-resources'
export const fontEndHead = '/app/home/font-end/font-end-head'
export const pageMainTop = '/app/home/font-end/font-end-mainTop'
export const pageMainCenter = '/app/home/font-end/font-endCenter'
export const pageMember = '/app/home/font-end/font-end-page-member'
export const fontEndJoinus = '/app/home/font-end/font-end-joinus'
export const gameMid = '/app/home/game/Mid'
export const gameContain = '/app/home/game/Contain'
export const gameBottom = '/app/home/game/Bottom'